import { Callout } from '@/components/docs/Callout';
import { Code } from '@/components/docs/Code';
import { DevToggle } from '@/components/docs/DevToggle';
import { Table } from '@/components/docs/Table';

export default function VendorSyncNormalization() {
  return (
    <div className="space-y-10">
      <section className="space-y-4">
        <h1 className="text-3xl font-semibold text-foreground">Normalization model</h1>
        <p className="text-muted-foreground">
          NormalizedProduct is the contract shared between Ops, adapters and downstream systems. Keep every field predictable
          so approvals travel smoothly from preview to apply.
        </p>
        <Callout tone="info">
          Ops sees NormalizedProduct in the registry grid. Any null or missing values surface as validation warnings and block
          apply runs until fixed.
        </Callout>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-foreground">Shape at a glance</h2>
        <Table
          columns={['Field', 'Type', 'Notes']}
          rows={[
            [<code key="id">id</code>, <span key="type">string</span>, <span key="notes">Stable identifier generated by Clairity. Use vendor SKU when possible.</span>],
            [<code key="vendorProductId">vendorProductId</code>, <span key="type">string</span>, <span key="notes">Raw vendor primary key for traceability.</span>],
            [<code key="status">status</code>, <span key="type">'active' | 'inactive' | 'draft'</span>, <span key="notes">Controls downstream availability. Ops toggles this to pause assortment.</span>],
            [<code key="pricing">pricing</code>, <span key="type">object</span>, <span key="notes">Requires <code>currency</code> + <code>list</code>. Wholesale optional.</span>],
            [<code key="inventory">inventory</code>, <span key="type">object</span>, <span key="notes">Quantity nullable. Provide location array when vendor shares per-store counts.</span>],
            [<code key="attributes">attributes</code>, <span key="type">object</span>, <span key="notes">Flat key/value pairs (color, material, frameShape). Avoid nested objects.</span>],
            [<code key="raw">raw</code>, <span key="type">object</span>, <span key="notes">Full vendor payload for audit and debugging.</span>],
          ]}
        />
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-foreground">Example payload</h2>
        <Code
          language="json"
          value={`{
  "id": "moscot-lemtosh-demo",
  "vendorProductId": "LEMTOSH-49",
  "name": "Lemtosh 49",
  "brand": "Moscot",
  "description": "Acetate frame with keyhole bridge and diamond rivets.",
  "category": "frames",
  "status": "active",
  "sku": "MOS-LEMTOSH-49-TORT",
  "pricing": {
    "currency": "USD",
    "list": 295,
    "wholesale": 145
  },
  "inventory": {
    "quantity": 18,
    "locations": [
      { "id": "flagship", "available": 6 },
      { "id": "brooklyn", "available": 5 },
      { "id": "online", "available": 7 }
    ]
  },
  "attributes": {
    "color": "Tortoise",
    "shape": "Panto",
    "material": "Acetate",
    "fit": "Wide"
  },
  "media": [
    { "url": "https://cdn.clairity.dev/moscot/lemtosh-front.jpg", "primary": true },
    { "url": "https://cdn.clairity.dev/moscot/lemtosh-side.jpg", "primary": false }
  ],
  "raw": {
    "id": "LEMTOSH-49",
    "title": "Lemtosh 49",
    "colorway": "Tortoise",
    "material": "Acetate",
    "price": 295,
    "inventory": [
      { "location": "flagship", "qty": 6 },
      { "location": "brooklyn", "qty": 5 },
      { "location": "online", "qty": 7 }
    ]
  }
}`}
        />
        <p className="text-xs text-muted-foreground">
          Attributes stay flat so Ops can search and bulk edit quickly. Use predictable keys (color, size, baseCurve, coating)
          across vendors to unlock reporting.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-foreground">Validation guardrails</h2>
        <ul className="list-disc space-y-3 pl-6 text-sm text-foreground/80">
          <li>
            Pricing: require <code>currency</code> and <code>list</code>. Reject <code>list</code> values below 0 and surface a
            warning when wholesale is greater than list.
          </li>
          <li>
            Inventory: allow <code>null</code> quantity for vendors without stock feeds. When locations exist, include both
            <code>id</code> and <code>available</code> fields.
          </li>
          <li>
            Media: limit to 10 assets per item to keep preview performance crisp. Mark exactly one asset as <code>primary</code>.
          </li>
          <li>
            Raw payload: keep the structure untouched. Engineers rely on it when debugging vendor schema shifts.
          </li>
        </ul>
        <DevToggle title="Developer details — schema snippet">
          <Code
            language="typescript"
            value={`export const normalizedProductSchema = z.object({
  id: z.string(),
  vendorProductId: z.string(),
  name: z.string().min(2),
  brand: z.string().min(1),
  description: z.string().nullable(),
  category: z.enum(['frames', 'lenses', 'contacts', 'accessories']),
  status: z.enum(['active', 'inactive', 'draft']),
  sku: z.string().nullable(),
  pricing: z.object({
    currency: z.string().length(3),
    list: z.number().positive(),
    wholesale: z.number().positive().nullable(),
  }),
  inventory: z
    .object({
      quantity: z.number().int().nullable(),
      locations: z
        .array(z.object({ id: z.string(), available: z.number().int().nonnegative() }))
        .max(10),
    })
    .default({ quantity: null, locations: [] }),
  attributes: z.record(z.string(), z.string()),
  media: z.array(z.object({ url: z.string().url(), primary: z.boolean() })).max(10),
  raw: z.record(z.any()),
});`}
          />
        </DevToggle>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-foreground">Common pitfalls</h2>
        <Callout tone="danger">
          Avoid mutating <code>raw</code> or dropping vendor keys. Ops and engineers reference it to replay bugs. If a payload
          is too large, store the original in object storage and keep a link in <code>raw.__sourceUrl</code>.
        </Callout>
        <ul className="list-disc space-y-3 pl-6 text-sm text-foreground/80">
          <li>Do not coerce nulls into empty strings. The registry highlights nulls so Ops can add overrides.</li>
          <li>Watch for locale-specific decimals. Normalize to a numeric type before returning.</li>
          <li>Ensure <code>status</code> toggles with vendor flags (e.g., discontinued) rather than Ops overrides.</li>
        </ul>
      </section>
    </div>
  );
}
